service: serverless-izettle-integrations

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

functions:
  postWebhook:
    handler: handler.postWebhook
    events:
      - http:
          path: /webhook
          method: post
          cors: true
    environment:
      SLACK_WEBHOOK_URL:  ${env:SLACK_WEBHOOK_URL}
      SLACK_WEBHOOK_ICON:  ${env:SLACK_WEBHOOK_ICON}
